version: "3"
services:
  node:
    build: ./node
    container_name: netcoin-node
    ports:
      - "26657:26657"
      - "8545:8545"
    volumes:
      - ./data:/data
    command: ["./netcoind"]

  explorer:
    build: ./explorer
    container_name: netcoin-explorer
    ports:
      - "3000:3000"
    depends_on:
      - node

  wallet:
    build: ./wallet-web
    container_name: netcoin-wallet
    ports:
      - "5173:5173"
    depends_on:
      - node
